#!/bin/sh

rm hardware/armtimer/armtimer.o
rm hardware/baregpio/baregpio.o
rm busywait/busywait.o
rm str/str.o
rm calc/calc.o
rm console/console.o
rm mailbox/mailbox.o
rm mem/mem.o
rm miniuart/miniuart.o
rm pl011uart/pl011uart.o
rm statetoggle/statetoggle.o
rm tape/tape_fill_buf.o
rm tape/tape_sample.o
rm tape/tape_send.o
rm tape/tape_send_buf.o
rm tape/tape_init.o
rm tape/tape_receive_buf.o
rm tape/tape_receive.o
rm tape/tape_extract_buf.o
rm ui/ui_send_sample.o
rm ui/ui_receive_test.o
rm ui/ui_send_test.o
rm ui/ui_terminal_to_commodore.o
rm ui/ui_commodore_to_terminal.o
rm ui/ui.o
rm alloc/alloc.o
rm alloc/alloc_mem.o
rm alloc/nodemem.o
rm video/video.o
rm watchdog/watchdog.o
rm xmodem/xmodem.o
rm ymodem/ymodem.o

rm boot.o
rm kernel_main.o
rm kernel.elf
rm kernel.img
rm kernel7.img
rm kernel.ihx
